### ISSUE TITLE
Cannot parse an ISO-8601 date if there are too many nano-of-second digits

### ISSUE THREAD

**Issue by Cardu** [buildo/toctoc#62]
## description
If the server returns the instant with too many nano-of-seconds, like 6, and the front-end project is using ```'buildo-toctoc/lib/metarpheus/api'```, it will result in tcomb error.

The formatter usually adopted in the backend (below scala libraries) is [Java ISO_INSTANT](https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html#ISO_INSTANT) that follows the ISO-8601 standard and prints "The nano-of-second outputs zero, three, six or nine digits digits as necessary"

## how to reproduce
mock your api so that they will return a token with 6 digits, like:
```
{
	"accessToken": {
		"value": "LFXcQLBULQ8clVFweD7zBsMui4WFl70zJcaqx73U7TOCE2LsUCb9FoHIquVSs8nw",
		"expiresAt": "2019-01-04T18:25:10.461198Z"
	},
	"refreshToken": {
		"value": "LFXcQLBULQ8clVFweD7zBsMui4WFl70zJcaqx73U7TOCE2LsUCb9FoHIquVSs8nw",
		"expiresAt": "2019-01-04T18:25:10.461387Z"
	}
}
```

**Comment by bytecodeguru** [comment]
Won't fix.
